config/routes.rb
GitAtMe::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  post "features/:feature_id/update_slide_order" => "features#update_slide_order"
  post "features/:feature_id/uploads/destroy-on-back" => "uploads#destroy_on_back"
  post "features/:feature_id/snippets/destroy-on-back" => "uploads#destroy_on_back"

  get "/login"  => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  resources :projects do
    resources :features, :shallow => true do
      resources :slides, :only => :new
      resources :snippets
      resources :uploads
    end
    resources :uploads
  end

  resources :users do
    resources :technologies, only: [:show]
    resources :repos, :shallow => true, only: [:show]
  end

  get "/technologies/:tech_name" => 'projects#filtered', as: "filtered_path"

  root :to => 'projects#landing'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :github_id

  has_many :repos
  has_many :user_projects
  has_many :projects, :through => :user_projects
  has_many :technologies, :through => :features

  validates :email, :uniqueness => true
  validates :name, :github_id, :token, :avatar_url, :presence => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :update, :allow_nil => true

  after_destroy :prune_repos, :disassociate_projects

  def tech_features(chosen_tech)
    Feature.joins(:technologies).where(:user_id => self.id, :technologies => {:name => chosen_tech.name})
  end

  def editable_by?(user)
    self == user
  end

  def can?(action, object)
    object.send("#{action}able_by?", self)
  end

  def features
    user_projects.collect(&:features).flatten
  end

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

  def self.from_omniauth(auth)
    where(:github_id => auth["uid"]).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.github_id = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.email = auth["info"]["email"]
      user.avatar_url = auth["info"]["image"]
      user.token = auth["credentials"]["token"]
      user.registered = false
    end
  end

  def prune_repos
    self.repos.each { |repo| !repo.project_id ? repo.destroy : repo.user_id = nil }
  end

  def associate_with_existing_projects ## Maybe use an error catch for each on NilClass so we can iterate over the original database response
    old_projects = UserProject.where(:contributor_github_id => self.github_id)
    if !old_projects.empty?
      old_projects.each do |old_project|
        old_project.user_id = self.id
        old_project.save
      end
    end
  end

  def disassociate_projects
    self.user_projects.each { |user_project| user_project.user_id = nil }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :only => [:new, :index, :show, :create]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
     @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @features = @user.features

    respond_to do |format|
      format.html {@user} # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

    redirect_to current_user if !current_user.can?(:edit, @user)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        login(@user)
        @user.associate_with_existing_projects
        Repo_scraper.new(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        GgMailer.registration_confirmation(@user).deliver if @user.registered == false
        @user.registered = true
        @user.save

        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    reset_session
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase if user.email
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=96"
    end
  end

  def link_to_user_description(user)
    "<a href= \"/users/#{user.id}\" class=\"thumbnail with-content\"><img alt=\"Photo-card-big-1\" src=#{avatar_url(user)}>
    <div class=\"thumbnail-hover-w\">
    <div class=\"thumbnail-hover-title\">  #{user.name} </div>
    </div>
    </a>".html_safe
  end

  def show_projects(user)
    if user == current_user
      if user.projects.empty?
        render :partial => "users/gallery/my_project_explanation"
      else
        render :partial => "users/gallery/user_gallery", :locals => { :page_user => user }
      end
    else
      render :partial => "users/gallery/user_projects", :locals => {:user => user}
    end
  end

  def get_the_projects(user)
    login(user)
    user.associate_with_existing_projects
    Repo_scraper.new(user)
  end

  def show_projects_or_repos(user)
    if user == current_user
      render :partial => "users/gallery/user_repos", :locals => { :page_user => user }
    else
      render :partial => "users/gallery/user_projects_information", :locals => {:user => user}
    end
  end
end

app/views/users/gallery/_my_project_explanation.html.erb
<div class="section-wrapper-show">
<% if current_user == @user %>
  <h1>My Projects</h1>
  <h2>Welcome to your Gallery Page.</h2>

  <p class="lead">
    This page will eventually show off your projects. In order to create a project, please see the sidebar to the right which shows all available repos we found on your github page and choose one to get started. We will notify your github collaborators so they can participate.
    <br><br>
    You and your collaborators will be able to edit your project's basic information and create features that showcase your skills. There will be a slider that contains all features you and your collaborators have made for your project. Below this, there will be a slide carousel showing the explanation, code snippet or images associated with each feature.
  </p>

  <div class="clearfix"></div>
  <h3>Tell your mates and show off your project!</h3>
  <h4 class="pull-right">The Git Gallery Team</h4>
<% else %>
  <h2><%= @user.name %> hasn't created any repos yet...</h2>
  <h3>Check back soon!</h3>
<% end %>

</div>

app/views/users/gallery/_user_gallery.html.erb
<div class="section-wrapper clearfix">

  <h3 class="section-header">Your Projects</h3>

  <% @user.projects.each do |project| %>

    <div class="span4">
      <div class="user-project">
        <%= link_to project.name.truncate(20), project_path(project) %>
        <%= project_image(project) %>
        <p><%= show_truncated_project_description(project) %></p>
      </div>
    </div>

  <% end %>

</div>

app/views/users/gallery/_user_projects.html.erb
  <div class="section-wrapper clearfix">
    <h3 class="section-header">Welcome to the Gallery of <%= user.name.capitalize %></h3>
    <% user.projects.each_with_index do |project, index| %>
      <%= render :partial => "projects/partials/index_card", :locals => { :project => project, :index => index } %>
    <% end %>
  </div>

app/views/users/gallery/_user_projects_information.html.erb
<div class="blog-categories widget-tp">
  <h3>Project Preview</h3>
  <div class="project-full-description">
    <% user.projects.each_with_index do |project, index| %>
      <%= render :partial => "projects/partials/project_full_description", :locals => { :project => project, :index => index } %>
    <% end %>
  </div>
</div>

app/views/users/gallery/_user_repos.html.erb
<% current_user_var = current_user %>
<div class="repo-listing">
  <div class="blog-categories widget-tp">
    <h3>Build a Project!</h3>

    <ul>
      <li>
        <div class="user-repo-url">
          <p class="lead">View on GitHub</p>
        </div>
        <div class="user-repo-build">
         <p class="lead">Build</p>
        </div>
      </li>

      <% Repo.where(:user_id => page_user.id).each do |repo| %>
        <% if !is_project?(repo) %>
          <li>
            <div class="user-repo-url">
              <%= link_to repo.name.truncate(25), repo.html_url, id: "#{repo.name}", :target => "_blank" %>
            </div>
            <div class="user-repo-icon">
               <%= link_to "", projects_path(:repo_id => repo.id), :method => :post, :"data-name" => "#{repo.name}", class:"icon-plus-sign" %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>