config/routes.rb
GitAtMe::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  post "features/:feature_id/update_slide_order" => "features#update_slide_order"
  post "features/:feature_id/uploads/destroy-on-back" => "uploads#destroy_on_back"
  post "features/:feature_id/snippets/destroy-on-back" => "uploads#destroy_on_back"

  get "/login"  => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  resources :projects do
    resources :features, :shallow => true do
      resources :slides, :only => :new
      resources :snippets
      resources :uploads
    end
    resources :uploads
  end

  resources :users do
    resources :technologies, only: [:show]
    resources :repos, :shallow => true, only: [:show]
  end

  get "/technologies/:tech_name" => 'projects#filtered', as: "filtered_path"

  root :to => 'projects#landing'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :source, :description, :features, :creator_id

  has_one :repo

  has_many :project_technologies, :dependent => :destroy
  has_many :technologies, :through => :project_technologies

  has_many :user_projects
  has_many :users, :through => :user_projects

  has_one :upload, :as => :uploadable, :dependent => :destroy

  validates :name, :presence => true

  def make_from(repo)
    self.repo = repo
    self.get_description
    self.get_technologies
    self.get_contributors
    repo.project_id = self.id
    repo.save
  end

  def this_user_features(chosen_user)
    Feature.joins(:project).where(:project_id => self.id, :user_id => chosen_user.id)
  end

  # def self.technologies(tech_name)
  #   # select p.name from projects p
  #   # join features f on
  #   # f.project_id = p.id
  #   self.joins("JOIN features ON features.project_id = projects.id").
  #   # join feature_technologies ft
  #   # on ft.feature_id = f.id
  #   joins("JOIN feature_technologies ON feature_technologies.feature_id = features.id").
  #   # join technologies t on
  #   # t.id = ft.technology_id
  #   joins("JOIN technologies ON technologies.id = feature_technologies.technology_id").
  #   # where t.name = "Rails"
  #   where('technologies.name' => tech_name)
  # end

  def self.find_by_repo(repo)
    previous_repo = Repo.joins(:project).where(:github_id => repo.github_id).first
    previous_project = previous_repo.project if previous_repo
  end

  def features
    user_projects.collect(&:features).flatten
  end

  def get_technologies
    self.creator
    techs = JSON.parse(open("https://api.github.com/repos/#{creator.name}/#{self.name}/languages?access_token=#{creator.token}").read)
    techs.each do |technology, mystery_number|
      saved_tech = Technology.where(:name => technology).first || Technology.create(:name => technology)
      project_tech = ProjectTechnology.create(:project_id => self.id, :technology_id => saved_tech.id)
    end
  end

  def creator
    self.repo.user
  end

  def get_contributors
    contributors = JSON.parse(open("https://api.github.com/repos/#{creator.name}/#{self.name}/contributors?access_token=#{creator.token}").read)

    contributors.each do |contributor|
      contributor_info = JSON.parse(open("https://api.github.com/users/#{contributor["login"]}?access_token=#{creator.token}").read)
      userproject = UserProject.find_or_create_by_project_id(:project_id => self.id, :contributor_github_id => contributor_info["id"])
      user = User.where(:github_id => userproject.contributor_github_id).first
      userproject.user_id = user.id if user
      userproject.save

      mail_on_new_project(self, contributor_info)
    end
  end

  def mail_on_new_project(project, contributor_info)
    contributor_if_present = project.users.where(:github_id => contributor_info["id"]).first || contributor_info
    GgMailer.new_project(self, contributor_if_present).deliver if !contributor_if_present["email"].nil?
  end

  def editable_by?(user)
    self.users.include?(user)
  end

  def default_description
    self.description || "This is a work in progress."
  end

  def get_description
    github_description = JSON.parse(open("https://api.github.com/repos/#{creator.name}/#{self.name}").read)["description"]
    if github_description.nil? || github_description.empty?
     return self.default_description
    else
      self.description =  github_description
    end
    self.save
    self.description
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :login_required, :only => [:index, :show, :landing]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }

    @features = @project.features
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @upload = Upload.find_or_create_by_id(params[:id])
    @uploadable = @project
  end

  # POST /projects
  # POST /projects.json
  def create  ### This logic needs to be abstracted
    @repo = Repo.find(params[:repo_id])
    @project = Project.new
    @project.name = @repo.name

    respond_to do |format|
       if @project.save
        @project.make_from @repo
        format.html { redirect_to project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @project.name = params[:project][:name]
    @project.description = params[:project][:description]

    @project.upload.destroy if @project.upload
    image = Upload.new(:image => params[:project][:image].tempfile) if params[:project][:image]
    image.save if image
    @project.upload = image

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully updated')}
        format.json { respond_with_bip(@project)}
      else
        format.html { render "edit"}
        format.json { respond_with_bip(@project)}
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def filtered
    @projects = Project.technologies(params[:tech_name])
  end

  def landing
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper


	def link_to_project_image(project)
		if project.upload
			link_to image_tag(project.upload.image_url.to_s), project_path(project)
		else
			link_to image_tag("http://octodex.github.com/images/octocat-de-los-muertos.jpg"), project_path(project)
		end
	end

	def project_image(project)
		if project.upload
			link_to( image_tag(project.upload.image_url.to_s), project_path(project))
		else
			link_to( image_tag("http://octodex.github.com/images/octocat-de-los-muertos.jpg"), project_path(project))
		end
	end

	def user_dependent_view(project, attribute)
		if project.editable_by?(current_user)
			render partial: "projects/hero/edit_project_#{attribute}", :locals => {:project => project}
		else
			project.send(attribute)
		end
	end

	def user_dependent_edit(project)
		if project.editable_by?(current_user)
			render partial: "projects/hero/edit_project_button", :locals => {:project => project}
		end
	end

	def image_link(project)
		if project.upload
		 "#{project.upload.image_url.to_s}"
		else
			"http://octodex.github.com/images/octocat-de-los-muertos.jpg"
		end
	end

	def show_project_description(project)
		(project.description if project.description) || "a work in progress"
	end

	def show_truncated_project_description(project)
		show_project_description(project).truncate(30)
	end

	def show_project_technologies(project)
		render :partial => "projects/partials/technologies", :locals => { :project => project } if project.technologies.size > 0
	end

	def show_project_contributers(project)
		render :partial => "projects/partials/contributers", :locals => { :project => project } if project.users.size > 0
	end

	def default_description
		"Add a Description"
	end

	def no_slides_message(feature)
		current_user == feature.user ? "No Slides Yet! Add Some!" : "#{feature.user.name.split.first} hasn't added any slides yet!"
	end
end

app/views/projects/_edit_hero.html.erb
<section class="hero-unit">

<div class="row-fluid">
  <div id="hero-description" class="span12" >

<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="span3 hero-title">
    	<h1><%= best_in_place @project, :name, :type => :input %></h1>
      <h1 id="project-title"><%= render partial: "edit_project_title", :locals => {:f => f, :project => @project} %></h1>
    </div>

    <div class="hero_tags span9">
      <div class="row-fluid span12">
        <%= render "tech_tags" %>
      </div>
    </div>

    <div class="clearfix"></div>
    <div class="span8 proj-descript"><p><%= render partial: "edit_description", :locals => {:f => f, :project => @project} %></p></div>
    <div class="clearfix"></div>
    <div class="hero_contrib">
		<%= render "contributors" %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  </div>
</div>
</section>

app/views/projects/_features.html.erb
<div class="span12 feature-section">
  <div class="creator">
<% if @features.empty? && current_user %>
<h3 id="features-title" class="section-header">Add a New Feature To Your Project</h3>
<% elsif current_user%>
<h3 id="features-title" class="section-header">Features</h3>
<% end %>
    
    <%= link_to 'New', new_project_feature_path(@project) if current_user%>
  </div>

  <div id="features-slide">
    <% @project.features.each do |feat| %>
      <div class="feature">
        <h2 class="feature-card-title" data-name="<%= feat.title.downcase.gsub(" ", "_") %>">
          <%= feat.title %>
        </h2>
      </div>
    <% end %>
  </div>

  <div class="container-fluid ">
    <div class="row-fluid">
      <% @project.features.each do |feat| %>
        <div id="<%= feat.title.downcase.gsub(" ", "_") %>" class="span12 item1 carousel_container carousel-main">
          <div class="span8 carousel-slides">
            <%= render :partial => "carousel_slides", :locals => {:feature => feat} %>
          </div>
          <div class="span4 carousel-sidebar">
            <div class="top-sidebar">
              <h2><%= feat.user.name if feat.user %> </h2>
              <%= link_to (image_tag avatar_url(feat.user)), user_path(feat.user) if feat.user %>
              <p><em>Member since: <%= feat.user.created_at.strftime("%b %d %Y") if feat.user %></em></p>
            </div>
            <div class="bottom-sidebar">
              <h2>Feature Description</h2>
              <p><%= feat.description %></p>
              <h2>Feature Slides</h2>
              <ul>
                <% feat.slides_in_order.each do |slide| %>
                  <li><%= slide.name if slide %>  =><em>  <%= slide.class %></em></li>
                <% end %>
              </ul>
              <p>
                <em>Created on <%= feat.created_at.strftime("%A, %b %d %Y") %></em>
                <br>
                <em>Last updated on <%= feat.updated_at.strftime("%A, %b %d %Y") %></em>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_hero.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script></script>

<script>
$(document).ready(function() {
  /* Activating Best In Place */
  jQuery(".best_in_place").best_in_place();
});
</script>

<section class="hero-unit">

<div class="row-fluid">
  <div id="hero-description" class="span12" >

<%= user_dependent_view(@project, "name") %>

    <div class="span3 hero-title">

    </div>

    <div class="hero_tags span9">
      <div class="row-fluid span12">
        <%= render "tech_tags" %>
      </div>
    </div>

    <div class="clearfix"></div>
    <div class="span8 proj-descript">

<%= user_dependent_view(@project, "description") %>

    </div>
    <div class="clearfix"></div>
    <div class="hero_contrib">

      <%= render "contributors" %>
    </div>

  </div>

</div>
</section>

app/views/projects/edit.html.erb
<!-- Test -->
<div class="post-info clearfix">

<section class="section-wrapper stripped">
  <div class="container">
    <div class="row">
      <div class="span12 project-title-custom">
        <h3 class="section-header"><%= @project.name %></h3>
      </div>
      <%= form_for(@project, :html => {:class => "form-horizontal"}) do |f| %>
        <%= render :partial => "shared/error_messages", :locals => {:target => @project} %>

        <div class="span10" id="edit_project_white_card">
          <div class="white-card recent-post clearfix">
            <h5 class="recent-post-header">
              <%= f.label :name, "Project Title" %>
            </h5>
            <div class="post-info clearfix">
              <div class="text-field-custom"%>
                <%= f.text_field :name, :id => "edit_form_name" %>

                <h5 class="recent-post-header">
                  <%= f.label :image, "Display Image"%>
                </h5>
                <%= image_tag image_link(@project), :id => "edit_form_image", :class => "thumbnail" %>
                <div class="controls" id="image-submit-custom">

                  <%= f.file_field :image %>
                </div>

                <h5 class="recent-post-header">
                  <%= f.label :description, "Description"%>
                </h5>
                <div class="description-area-custom">
                  <%= f.text_area :description, :rows => 7, :id => "edit_form_text_area" %>
                </div>
              </div>

              <ul class="pager">
                <li class="next"> <%= f.submit "Confirm Info", :class => "btn btn-primary btn-extra pull-right post-btn"%></li>
              </ul>

              <!-- <a href="/theme_venera/single_post" class="btn btn-primary btn-extra pull-right post-btn">Confirm Info &gt;</a> -->
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/projects/index.html.erb
<div class="inline-custom">
  <div class="container user_show">
    <div class="row-fluid span12">

      <div class="span8 float-custom-left">

        <div class="bs-docs-example">

          <div class="section-wrapper clearfix">
            <h3 class="section-header">Projects</h3>
            <% @projects.each_with_index do |project, index| %>
              <%= render :partial => "projects/partials/index_card", :locals => { :project => project, :index => index } %>
            <% end %>
          </div>

        </div>

      </div>

      <div class="span3 float-custom-right">

        <div class="blog-categories widget-tp">
          <h3>Project Preview</h3>
          <div class="project-full-description">
            <% @projects.each_with_index do |project, index| %>
              <%= render :partial => "projects/partials/project_full_description", :locals => { :project => project, :index => index } %>
            <% end %>
          </div>
        </div>


      </div>

    </div>
  </div>
</div>

app/views/projects/old_index.html.erb
<section class="section-wrapper">
<div class="container">
<div class="row">
<div class="span12">
<h3 class="section-header">Projects</h3>
</div>
<% @projects.each do |project| %>
      <div class="span4">
      <div class="white-card recent-post clearfix">
      <h5 class="recent-post-header">
         <a href="<%= project_path(project)%>"><%= project.name %></a>
      </h5>
      <div class="post-info clearfix">
      </div>
<%= project_image(project) %>

  <p class="post-content separated"><%= project.description %></p>
      <div class="technologies-custom">
    <% project.technologies.each do |tech| %>
    <span class="label"><%=tech.name%></span>
    <% end %>
  </div>
      </div>
      </div>
<%end %>
</div>
</div>
</section>

app/views/projects/old_show.html.erb
<div class="carousel-inner slider-w">
	<p id="notice" class="gg-notice">
		<%= notice %>
	</p>
</div>

<div class="carousel slide over-something" id="homepage-carousel">
	<!-- Project Section Starts -->
	<div class="carousel-inner slider-w">
		<div class="active item">
			<div class="container">
				<h1 class="slider-header">
					<strong>
						<%= @project.name %>
					</strong>
				</h1>
				<%= link_to "See this project on GitHub", @project.repo.html_url, :target => "_blank" %>
				<h2 class="slider-sub-header">
				<ul class="inline tech">
					<% @project.technologies.each do |tech| %>
						<li><%= tech.name %><li>
					<% end %>
				</ul>
				</h2>
				<h3 class="gg-project-show-description-custom">
					<%= @project.description %>
				</h3>
				<div class="top-account-control visible-desktop">
					<%= link_to "Edit This Project", edit_project_path(@project), :class => "top-create-account" if @project.users.include?(current_user) %>
				</div>
			</div>
		</div>
	</div>
	<!-- Project Section End -->
	<!-- Contributers Section Start -->

	<div class="sub-slider-features">
		<div class="container">
			<div class="row">
				<div class="info-bullet">
					<h5>Contributors</h5>
			<!-- 		test -->
			<% @project.users.uniq.each do |user| %>
			<div class="avatar-custom">
					<figure>
						<%= link_to (image_tag avatar_url(user), title: "#{user.name}", rel: 'tooltip'), user_path(user) %>
						<figcaption>
							<h4><%= user.name.split(" ").first %></h4>
							<p>Team Lead</p>
						</figcaption>
					</figure>
			</div>
			<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Contributers Section End -->
</div>

<!-- Feature Carousel Starts Here -->
<section class="section-wrapper under-slider">
<div class="container">
	<div class="row">
		<div class="span12 span12-custom">
			<h3 class="section-header">Features</h3>
		</div>
		<div class="clearfix">
			<div class="accordion" id="accordion">
				<% @project.features.each_with_index do |feat, index| %>
				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#collapse<%=index%>">
							<%= feat.title.downcase.gsub(" ", "_") %>
							<%= image_tag avatar_url(feat.user), :class => "accordion-inline-avatar pull-left" %>
						</a>
					</div>
					<div class="accordion-body collapse" id="collapse<%=index%>">
						<div class="accordion-inner">
							<div class="span8">
								<h3 class="accordion-feat-title">BEHIND THE SCENES OF <%= feat.user.name.upcase %>'S <%= feat.title.upcase %></h3>
								<h4><strong>Feature Description:</strong></h4>
								<h4 class="accordion-feat-description-custom"><%= feat.description %></h4>
							</div>
							<div class="span2 accordion-feat-author">
								<h2 class="accordion-feat-name-custom">
									<%= feat.user.name if feat.user %>
								</h2>
								<%= link_to (image_tag avatar_url(feat.user), class: "img-circle"), user_path(feat.user) if feat.user %>
							</div>
							<div class="clearfix">
							</div>
						</div>
						<div class="accordion-inner">
							<div id="myCarousel<%=feat.id%>" class="carousel slide">
								<div class="carousel-inner">
									<% if feat.slides_in_order.any? %>
										<% feat.slides_in_order.each do |slide| %>
											<div class="item">
												<p class="accordion-feat-name-custom">
													<%= slide.name %>
												</p>
												<p class="accordion-feat-pagination">
													<%= slide.position + 1 %>
								          of
								          <%= feat.slides_in_order.length %>
												</p>
												<div class="accordion-feat-upload-custom">
													<%= snippet_or_upload_show(slide) %>
												</div>
												<h6 class="accordion-slide-description-custom">
													<%= slide.description %>
												</h6>
												<a class="left carousel-control" href="#myCarousel<%=feat.id%>" data-slide="prev">‹</a>
												<a class="right carousel-control" href="#myCarousel<%=feat.id%>" data-slide="next">›</a>
											</div>
										<% end %>
											<p class="top-account-control">
												<% if feat.user == current_user %>
													<%= link_to "Add Slides", new_feature_slide_path(feat), :class => "top-create-account" %><br><br>
													<%= link_to "Edit #{feat.title}", edit_feature_path(feat), :class => "top-create-account" %>
												<% end %>
											</p>
									<% else%>
										<div class="item">
											<p class="accordion-feat-name-custom">
												<%= no_slides_message(feat) %>
											</p>
											<p class="top-account-control">
												<%= link_to "Add Slides", new_feature_slide_path(feat), :class => "top-create-account" if feat.user == current_user %><br><br>
												<%= link_to "Edit #{feat.title}", edit_feature_path(feat), :class => "top-create-account" %>
											</p>
										</div>							
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<div class="top-account-control visible-desktop">
			<%= link_to "Add a Feature", new_project_feature_path(@project), :class => "top-create-account" if @project.users.include?(current_user) %>
		</div>
	</div>
</div>
</section>

<!-- Feature Carousel Ends Here -->



		
		
		
	

app/views/projects/show.html.erb
<div class="inline-custom">
  <div class="container user_show">
    <div class="row-fluid span12">

      <div class="span8 float-custom-left">

        <div class="bs-docs-example project-container">

          <div class="section-wrapper">
            <h3 class="section-header"><%= @project.name.upcase %></h3>
            <%= render :partial => "projects/partials/project_features", :locals => { :project => @project } %>

            <div class="top-account-control visible-desktop">
              <%= link_to "Add a Feature", new_project_feature_path(@project), :class => "top-create-account" if @project.users.include?(current_user) %>
            </div>
          </div>

        </div>

      </div>

      <div class="span3 float-custom-right">
        <div class="project-info-container">
          <h3>PROJECT INFORMATION</h3>
        <div class="information-container">
            <%= render :partial => "projects/partials/information", :locals => { :project => @project } %>
          </div>
        </div>

        <div class="blog-categories widget-tp">
          <h3>Slide Information</h3>
          <div class="project-full-description">
            <%= render :partial => "projects/partials/slide-information", :locals => { :project => @project } %>
          </div>
        </div>


      </div>

    </div>
  </div>
</div>